Update drawNameTag function and file used this function
aimpowered/ZoomCompanion pull request #26
Opened 2024-03-01 01:32 UTC by kexinF

@blickly Hi Ben, I saw your comment regarding the rebase of the drawNametag API. Because that main dev is relatively old, I created a new PR based on your request. 

In this PR, we revise the drawNametag function to take only 2 arguments: nametag and handWave.

By clearly defining what parameters are related to nametag or handWave, we expect to increase the readability of the function.

2024-03-02 00:01 UTC, blickly commented
Creating a new PR sounds good, but in that case, let's close https://github.com/aimpowered/ZoomCompanion/pull/24

2024-03-02 00:01 UTC, blickly requested changes

2024-03-02 18:46 UTC, kexinF commented on app/main/NameTag.tsx
> +// import drawNametag from "@/lib/drawNametag";
Solved

2024-03-02 18:47 UTC, kexinF commented on lib/drawNametag.ts
> +}
@blickly Yes, I have modified the code based on this structure. But I set waveText can also be null, this is only set to null when visible is null.

2024-03-03 00:40 UTC, blickly requested changes

2024-03-03 00:40 UTC, blickly commented on lib/drawNametag.ts
> +// export default function drawNametag(nameTagStatus:boolean, currentNameTag:string[], selectedWaveHand: number | null, waveHands: string[]): ImageData {
Let's remove the commented out code

2024-03-03 00:40 UTC, blickly commented on lib/drawNametag.ts
> +}
You can actually include the fact that disabled badges don't need text in the types themselves, like:
```suggestion
interface DisabledBadge {
  visible: false
}
interface EnabledHandWaveBadge {
  visible: true;
  waveText: string;
}
export type HandWaveBadge = DisabledBadge | EnabledHandWaveBadge;
```

2024-03-03 00:40 UTC, blickly commented on app/main/NameTag.tsx
> +    };
I find it a little clearer to not repeat the `selectedWaveHand !== null` check twice.  Maybe something like:
```suggestion
    const handWave: HandWaveBadge =
       selectedWaveHand !== null ?
           {visible: true, waveText: waveHands[selectedWaveHand]} :
           {visible: false};
```

If you agree, let's make the same change in page.tsx

2024-03-03 00:40 UTC, blickly commented on lib/drawNametag.ts
> +  if (handWave.visible && handWave.waveText) {
```suggestion
  if (handWave.visible) {
```

2024-03-05 20:14 UTC, kexinF commented on lib/drawNametag.ts
> +// export default function drawNametag(nameTagStatus:boolean, currentNameTag:string[], selectedWaveHand: number | null, waveHands: string[]): ImageData {
solved

2024-03-05 20:16 UTC, blickly approved these changes
LGTM

2024-03-05 20:16 UTC, merged