Correct the error in test code
aimpowered/ZoomCompanion pull request #28
Opened 2024-03-11 04:59 UTC by kexinF

2024-03-12 04:21 UTC, blickly requested changes

2024-03-12 04:21 UTC, blickly commented on app/main/page.tsx
I don't understand the changes to this file.

2024-03-12 04:21 UTC, blickly commented on app/main/NameTag.tsx
> +          checked={showNametag} // It ensures the switch visually changes when clicked
https://en.wikipedia.org/wiki/Don%27t_repeat_yourself

It looks like the checked state is set 4 different times in the code.  I think it should only be set at most once (doesn't a checkbox already keep track of it's own state)?

2024-03-12 04:21 UTC, blickly commented on app/main/NameTag.tsx
> +            role: 'switch',
According to https://mui.com/material-ui/react-switch/#accessibility, we should test that the assistive technology our users will use supports the `switch` role properly before setting this. Have we done that?

2024-03-12 04:21 UTC, blickly commented on __tests__/nametag.test.tsx
> -
According to https://mui.com/material-ui/react-switch/#accessibility, switches/checkboxes should always have associated labels.  Can we make the test check that as well?

2024-03-12 19:42 UTC, blickly commented on __tests__/nametag.test.tsx
> +    expect(element).toBeInTheDocument();
Can we check more specifically that the switch input and the element labeled "Name Tag" are the same component?

2024-03-12 21:25 UTC, kexinF commented on app/main/page.tsx
solved, reverted the changes and will be do that in next PR

2024-03-14 03:27 UTC, blickly approved these changes
Looks good

2024-03-14 03:28 UTC, merged